apache/skywalking-client-js

src/errors/ajax.ts
src/errors/index.ts
src/errors/js.ts
src/errors/promise.ts
src/monitor.ts
src/services/base.ts
src/services/report.ts
src/services/types.d.ts
src/types.d.ts

trace logs for ajax and promise error types, include fetch.
**screenshots**

Feat support ajax and promise error types

---

src/errors/index.ts
src/errors/resource.ts
src/errors/vue.ts
src/monitor.ts
src/services/base.ts

Support tracking resource and vue error
reference https://github.com/apache/skywalking/issues/4206
Screenshot

Feat: trace resource and vue error

---

src/errors/js.ts
src/errors/vue.ts
src/monitor.ts
src/performance/fmp.ts
src/performance/index.ts
src/performance/perf.ts
src/performance/type.d.ts
src/services/base.ts
src/services/constant.ts
src/services/types.d.ts
src/types.d.ts

Trace performance data
reference https://github.com/apache/skywalking/issues/4334
**screenshots**

Feat: Trace performance data

---

package.json
src/errors/ajax.ts
src/errors/js.ts
src/errors/promise.ts
src/errors/resource.ts
src/errors/vue.ts
src/monitor.ts
src/performance/fmp.ts
src/performance/index.ts
src/services/base.ts
src/services/types.d.ts
src/types.d.ts
webpack.config.js

Reference https://github.com/apache/skywalking/issues/4212
Update fields according to https://github.com/apache/skywalking-data-collect-protocol/blob/master/browser/BrowserPerf.proto
ClientMonitor.setPerformance({  
&ensp; reportUrl: 'http://test.com',
&ensp; service: 'skywalking-ui',  
&ensp; serviceVersion: 'v8.1.0',  
&ensp; pagePath: location.href,  
&ensp; autoSendPerf: true,  
&ensp; useFmp: true,  
});  
Screenshot

Feat: Trace PV

---

src/errors/ajax.ts
src/errors/js.ts
src/errors/promise.ts
src/errors/resource.ts
src/errors/vue.ts
src/monitor.ts
src/performance/fmp.ts
src/performance/index.ts
src/performance/type.d.ts
src/services/base.ts
src/services/report.ts
src/services/task.ts
src/types.d.ts

Update SDK for collector, fixes http bug, refactor code
```
ClientMonitor.register({
collector: 'http://localhost:8888',
service: 'test-ui',
pagePath: 'http://localhost:8080/',
serviceVersion: 'v1.0.0'
});
```
signed-off-by: Qiuxia Fan <qiuxiafan@apache.org>

fix: Update configure

---

src/services/report.ts

Resolves https://github.com/apache/skywalking/issues/5780

Fix: response status judge bug

---

CHANGES.md
README.md

docs: update readme

---

src/performance/index.ts
src/services/report.ts
src/services/task.ts
src/trace/segment.ts

Add a timer for reporting segments.
Fixes peer parameter and add report mode.

feat: add a timer for reporting segments

---

src/trace/segment.ts

Set initial parentSpanId to -1.

fix: update parentSpanId

---

src/monitor.ts
src/performance/index.ts

Fixes tracing perf of spa page report duplicate data to serve
Signed-off-by: Qiuxia Fan <qiuxiafan.apache.org>

fix: trace perf of spa page

---

README.md
src/errors/ajax.ts
src/interceptors/xhr.ts
src/monitor.ts
src/services/report.ts
src/trace/segment.ts
src/types.d.ts

Fixes parameters of peer  and service in segments.
Screenshot

fix: update parameters in segments

---

README.md
src/monitor.ts
src/trace/segment.ts
src/types.d.ts

Add tags for spans in segments.
Screenshot

feat: add tags for spans

---

CHANGES.md

docs: update 0.3.0 changes

---

NOTICE

docs: update year for NOTICE

---

README.md
package-lock.json
src/errors/frames.ts
src/monitor.ts
src/performance/index.ts
src/types.d.ts

Catch frames errors, including React, Angular, Vue. Reference https://github.com/apache/skywalking/issues/6607
Screenshot
Here is a demo https://github.com/Fine0830/angular-demo

feat: catch frames errors

---

src/trace/interceptors/fetch.ts

Update peer in Fetch interceptor.
Screenshot

fix: update peer in fetch 

---

CHANGES.md
package.json

Update CHANGES and version for v0.5.0

docs: update CHANGES and version

---

.github/workflows/build.yml
package-lock.json
package.json
webpack.config.js

Fixes https://github.com/apache/skywalking/issues/6927
Screenshot

build: upgrade packages

---

package-lock.json
package.json
webpack.config.js

Remove the plugin for the development environment when building for production

build: Separate production and development environments when building

---

src/trace/interceptors/fetch.ts

https://github.com/apache/skywalking/issues/7161

fix: headers could be null

---

src/services/base.ts
src/trace/interceptors/fetch.ts

Fixes https://github.com/apache/skywalking/issues/6990
Screenshots

fix: the firstReportedError is calculated with more types of errors 

---

CHANGES.md
package-lock.json
package.json

Update version and changes for releasing 0.6.0

docs: update version and changes

---

CHANGES.md
README.md
src/monitor.ts
src/services/base.ts
src/trace/segment.ts
src/types.d.ts

Implement https://github.com/apache/skywalking/issues/7284
Screenshot

feat: support setting time interval to report segments

---

CHANGES.md
src/trace/interceptors/fetch.ts
src/trace/interceptors/xhr.ts

fix apache/skywalking#7335

---

src/trace/interceptors/fetch.ts

fix apache/skywalking#7765

---

CHANGES.md
src/errors/js.ts

fix window.onerror TypeError

---

src/performance/fmp.ts
src/performance/index.ts
src/services/task.ts
src/trace/segment.ts

Fixes https://github.com/apache/skywalking/issues/8746 and https://github.com/apache/skywalking-client-js/pull/52#issuecomment-1085369243

fix: update metric and events

---

src/trace/interceptors/fetch.ts
src/trace/interceptors/xhr.ts
test/e2e.yaml
test/expected/dependency.yml
test/expected/trace-detail.yml

Optimized for skywalking v9, support for trace in browser dashboard.
https://github.com/apache/skywalking/pull/8819

Remove ServiceTag

---

package.json
src/monitor.ts
src/performance/fmp.ts
src/performance/index.ts
tsconfig.json

Refactor perf functions to enhance readability.
Screenshot

refactor: update perf functions

---

.github/workflows/build.yml
package-lock.json

Bump minimist and url-parse, and update package-lock with npm v8.
Signed-off-by: Qiuxia Fan <qiuxiafan@apahce.org>

build: bump packages and update package-lock with npm v8

---

src/errors/ajax.ts
src/errors/frames.ts
src/errors/js.ts
src/errors/promise.ts
src/errors/resource.ts
src/errors/vue.ts
src/monitor.ts
src/trace/interceptors/fetch.ts
src/trace/interceptors/xhr.ts
src/trace/segment.ts

Reset custom configurations when the router changed for SPA. Close https://github.com/apache/skywalking/issues/8876
Screenshots
error logs
trace logs

feat: reset custom configurations when the page router changed for SPA

---

README.md
src/monitor.ts
src/trace/interceptors/fetch.ts
src/trace/interceptors/xhr.ts
src/types.d.ts

Add api for supporting adding custom tags to spans.
Screenshots

feat: support adding custom tags to spans

---

src/errors/vue.ts
src/monitor.ts

Validate custom parameters, If types of the parameters are wrong, they will be reset to default values or `undefined`.

feat: validate custom parameters for `register`

---

package-lock.json
package.json
webpack.config.js

Fixes https://github.com/apache/skywalking-client-js/security/dependabot/19 and https://github.com/apache/skywalking-client-js/security/dependabot/21

build(deps): bump glob-parent, node-forge and webpack

---

CHANGES.md

docs: update changes for v1.0.0

---

src/performance/index.ts

Related https://github.com/apache/skywalking/issues/12020
Screenshot

feat: Add `isPV` to identify page view

---

README.md

docs: Fix doc link

---

src/errors/resource.ts

the resource error can't be catched, i fixed it

fix: can't catch the resource error

---

src/performance/index.ts
src/performance/type.ts
src/services/constant.ts
src/services/interactions.ts
src/services/observe.ts
src/services/types.ts

feat: Add INP metric and remove FID

---

README.md

Adjust readme for incoming 1.0 release
